// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: myhomepage/myhomepage.proto

package myhomepage

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMyNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountName   string                 `protobuf:"bytes,1,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyNameRequest) Reset() {
	*x = GetMyNameRequest{}
	mi := &file_myhomepage_myhomepage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyNameRequest) ProtoMessage() {}

func (x *GetMyNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_myhomepage_myhomepage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyNameRequest.ProtoReflect.Descriptor instead.
func (*GetMyNameRequest) Descriptor() ([]byte, []int) {
	return file_myhomepage_myhomepage_proto_rawDescGZIP(), []int{0}
}

func (x *GetMyNameRequest) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

type GetMyNameReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyNameReply) Reset() {
	*x = GetMyNameReply{}
	mi := &file_myhomepage_myhomepage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyNameReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyNameReply) ProtoMessage() {}

func (x *GetMyNameReply) ProtoReflect() protoreflect.Message {
	mi := &file_myhomepage_myhomepage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyNameReply.ProtoReflect.Descriptor instead.
func (*GetMyNameReply) Descriptor() ([]byte, []int) {
	return file_myhomepage_myhomepage_proto_rawDescGZIP(), []int{1}
}

func (x *GetMyNameReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetMyInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountName   string                 `protobuf:"bytes,1,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyInfoRequest) Reset() {
	*x = GetMyInfoRequest{}
	mi := &file_myhomepage_myhomepage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyInfoRequest) ProtoMessage() {}

func (x *GetMyInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_myhomepage_myhomepage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyInfoRequest.ProtoReflect.Descriptor instead.
func (*GetMyInfoRequest) Descriptor() ([]byte, []int) {
	return file_myhomepage_myhomepage_proto_rawDescGZIP(), []int{2}
}

func (x *GetMyInfoRequest) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

type GetMyInfoReply struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Name                  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MyFavoriteDevLanguage string                 `protobuf:"bytes,2,opt,name=myFavoriteDevLanguage,proto3" json:"myFavoriteDevLanguage,omitempty"`
	EnglishName           string                 `protobuf:"bytes,3,opt,name=english_name,json=englishName,proto3" json:"english_name,omitempty"`
	ChineseName           string                 `protobuf:"bytes,4,opt,name=chinese_name,json=chineseName,proto3" json:"chinese_name,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetMyInfoReply) Reset() {
	*x = GetMyInfoReply{}
	mi := &file_myhomepage_myhomepage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyInfoReply) ProtoMessage() {}

func (x *GetMyInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_myhomepage_myhomepage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyInfoReply.ProtoReflect.Descriptor instead.
func (*GetMyInfoReply) Descriptor() ([]byte, []int) {
	return file_myhomepage_myhomepage_proto_rawDescGZIP(), []int{3}
}

func (x *GetMyInfoReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetMyInfoReply) GetMyFavoriteDevLanguage() string {
	if x != nil {
		return x.MyFavoriteDevLanguage
	}
	return ""
}

func (x *GetMyInfoReply) GetEnglishName() string {
	if x != nil {
		return x.EnglishName
	}
	return ""
}

func (x *GetMyInfoReply) GetChineseName() string {
	if x != nil {
		return x.ChineseName
	}
	return ""
}

type SetMyInfoRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Name                  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MyFavoriteDevLanguage string                 `protobuf:"bytes,2,opt,name=myFavoriteDevLanguage,proto3" json:"myFavoriteDevLanguage,omitempty"`
	EnglishName           string                 `protobuf:"bytes,3,opt,name=english_name,json=englishName,proto3" json:"english_name,omitempty"`
	ChineseName           string                 `protobuf:"bytes,4,opt,name=chinese_name,json=chineseName,proto3" json:"chinese_name,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SetMyInfoRequest) Reset() {
	*x = SetMyInfoRequest{}
	mi := &file_myhomepage_myhomepage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetMyInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetMyInfoRequest) ProtoMessage() {}

func (x *SetMyInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_myhomepage_myhomepage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetMyInfoRequest.ProtoReflect.Descriptor instead.
func (*SetMyInfoRequest) Descriptor() ([]byte, []int) {
	return file_myhomepage_myhomepage_proto_rawDescGZIP(), []int{4}
}

func (x *SetMyInfoRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SetMyInfoRequest) GetMyFavoriteDevLanguage() string {
	if x != nil {
		return x.MyFavoriteDevLanguage
	}
	return ""
}

func (x *SetMyInfoRequest) GetEnglishName() string {
	if x != nil {
		return x.EnglishName
	}
	return ""
}

func (x *SetMyInfoRequest) GetChineseName() string {
	if x != nil {
		return x.ChineseName
	}
	return ""
}

type SetMyInfoReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetMyInfoReply) Reset() {
	*x = SetMyInfoReply{}
	mi := &file_myhomepage_myhomepage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetMyInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetMyInfoReply) ProtoMessage() {}

func (x *SetMyInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_myhomepage_myhomepage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetMyInfoReply.ProtoReflect.Descriptor instead.
func (*SetMyInfoReply) Descriptor() ([]byte, []int) {
	return file_myhomepage_myhomepage_proto_rawDescGZIP(), []int{5}
}

func (x *SetMyInfoReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_myhomepage_myhomepage_proto protoreflect.FileDescriptor

const file_myhomepage_myhomepage_proto_rawDesc = "" +
	"\n" +
	"\x1bmyhomepage/myhomepage.proto\x12\x0eapi.myhomepage\x1a\x1cgoogle/api/annotations.proto\"5\n" +
	"\x10GetMyNameRequest\x12!\n" +
	"\faccount_name\x18\x01 \x01(\tR\vaccountName\"$\n" +
	"\x0eGetMyNameReply\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"5\n" +
	"\x10GetMyInfoRequest\x12!\n" +
	"\faccount_name\x18\x01 \x01(\tR\vaccountName\"\xa0\x01\n" +
	"\x0eGetMyInfoReply\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x124\n" +
	"\x15myFavoriteDevLanguage\x18\x02 \x01(\tR\x15myFavoriteDevLanguage\x12!\n" +
	"\fenglish_name\x18\x03 \x01(\tR\venglishName\x12!\n" +
	"\fchinese_name\x18\x04 \x01(\tR\vchineseName\"\xa2\x01\n" +
	"\x10SetMyInfoRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x124\n" +
	"\x15myFavoriteDevLanguage\x18\x02 \x01(\tR\x15myFavoriteDevLanguage\x12!\n" +
	"\fenglish_name\x18\x03 \x01(\tR\venglishName\x12!\n" +
	"\fchinese_name\x18\x04 \x01(\tR\vchineseName\"*\n" +
	"\x0eSetMyInfoReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xd9\x02\n" +
	"\n" +
	"Myhomepage\x12v\n" +
	"\tGetMyName\x12 .api.myhomepage.GetMyNameRequest\x1a\x1e.api.myhomepage.GetMyNameReply\"'\x82\xd3\xe4\x93\x02!\x12\x1f/myhomepage/name/{account_name}\x12g\n" +
	"\tGetMyInfo\x12 .api.myhomepage.GetMyInfoRequest\x1a\x1e.api.myhomepage.GetMyInfoReply\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/myhomepage/info\x12j\n" +
	"\tSetMyInfo\x12 .api.myhomepage.SetMyInfoRequest\x1a\x1e.api.myhomepage.SetMyInfoReply\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/myhomepage/infoB9\n" +
	"\x0eapi.myhomepageP\x01Z%demo2kratos/api/myhomepage;myhomepageb\x06proto3"

var (
	file_myhomepage_myhomepage_proto_rawDescOnce sync.Once
	file_myhomepage_myhomepage_proto_rawDescData []byte
)

func file_myhomepage_myhomepage_proto_rawDescGZIP() []byte {
	file_myhomepage_myhomepage_proto_rawDescOnce.Do(func() {
		file_myhomepage_myhomepage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_myhomepage_myhomepage_proto_rawDesc), len(file_myhomepage_myhomepage_proto_rawDesc)))
	})
	return file_myhomepage_myhomepage_proto_rawDescData
}

var file_myhomepage_myhomepage_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_myhomepage_myhomepage_proto_goTypes = []any{
	(*GetMyNameRequest)(nil), // 0: api.myhomepage.GetMyNameRequest
	(*GetMyNameReply)(nil),   // 1: api.myhomepage.GetMyNameReply
	(*GetMyInfoRequest)(nil), // 2: api.myhomepage.GetMyInfoRequest
	(*GetMyInfoReply)(nil),   // 3: api.myhomepage.GetMyInfoReply
	(*SetMyInfoRequest)(nil), // 4: api.myhomepage.SetMyInfoRequest
	(*SetMyInfoReply)(nil),   // 5: api.myhomepage.SetMyInfoReply
}
var file_myhomepage_myhomepage_proto_depIdxs = []int32{
	0, // 0: api.myhomepage.Myhomepage.GetMyName:input_type -> api.myhomepage.GetMyNameRequest
	2, // 1: api.myhomepage.Myhomepage.GetMyInfo:input_type -> api.myhomepage.GetMyInfoRequest
	4, // 2: api.myhomepage.Myhomepage.SetMyInfo:input_type -> api.myhomepage.SetMyInfoRequest
	1, // 3: api.myhomepage.Myhomepage.GetMyName:output_type -> api.myhomepage.GetMyNameReply
	3, // 4: api.myhomepage.Myhomepage.GetMyInfo:output_type -> api.myhomepage.GetMyInfoReply
	5, // 5: api.myhomepage.Myhomepage.SetMyInfo:output_type -> api.myhomepage.SetMyInfoReply
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_myhomepage_myhomepage_proto_init() }
func file_myhomepage_myhomepage_proto_init() {
	if File_myhomepage_myhomepage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_myhomepage_myhomepage_proto_rawDesc), len(file_myhomepage_myhomepage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_myhomepage_myhomepage_proto_goTypes,
		DependencyIndexes: file_myhomepage_myhomepage_proto_depIdxs,
		MessageInfos:      file_myhomepage_myhomepage_proto_msgTypes,
	}.Build()
	File_myhomepage_myhomepage_proto = out.File
	file_myhomepage_myhomepage_proto_goTypes = nil
	file_myhomepage_myhomepage_proto_depIdxs = nil
}
